services:
  # ============================================
  # Основной сервис разработки (Dev Container)
  # ============================================
  dev:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: python_localization_KCD2_dev
    hostname: kcd2_localization_client
    volumes:
      - ./workspace:/workspace
      - ./.docker/nvim:/home/dev/.config/nvim
      - ./.docker/scripts:/home/dev/.scripts:ro
      - /mnt/MyDownloads/000temp/Localization:/workspace/localization
      # - /mnt/kcd2:/workspace/kcd2:ro
      - sqlite_data:/db
      - dev-home:/home/dev
    env_file:
      - .env
    tty: true
    stdin_open: true
    command: poetry run python app/main.py
    # command: ["zsh"]

  # translator:
  #   container_name: python_localization_KCD2_translator
  #   extends:
  #     service: dev
  #   command: ["/workspace/.venv/bin/python", "/workspace/translate_wav.py"]

# ============================================
# Тома для сохранения данных
# ============================================
volumes:
  dev-home:
  sqlite_data:

