"""add model en_oggs

Revision ID: eb08c6c9ac74
Revises: 
Create Date: 2026-06-18 15:02:11.579750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb08c6c9ac74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('en_oggs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('en_oggs')
    # ### end Alembic commands ###
